### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by Mitchelllund** [Mitchelllund/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create a Index.html, styles.css and main.js files
- [x] Set the background color to green
- [x] Place the image of a race car in the top left corner
- [x] Make sure that the image is the appropriate size for the page.
