### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by Mitchelllund** [Mitchelllund/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create CSS styling in order for each of the cars positions.
- [x] Create a data model for the car that stores the positions.
- [x] Listen for 'keydown' events on the document.
- [x] Update the position of the car based on which key was pressed.
- [x] Assign the car position to the data model
