### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by Mitchelllund** [Mitchelllund/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Apply `position: absolute` to the car img.
- [x] Add a location to your data model to hold the car's x and y coordinates on the page.
- [x] Listen for a spacebar `'keydown'` event on the document.
- [x] Change the car img left property in html to move to the img.
- [x] Use `setInterval()` method to move the car every 16 milleseconds.
